[build]
  # Build settings for static site
  publish = "."
  command = "echo 'No build required for static site'"

[build.environment]
  # Environment variables for build
  NODE_VERSION = "18"

[[redirects]]
  # Redirect root to login page
  from = "/"
  to = "/login.html"
  status = 200

[[redirects]]
  # Handle SPA routing - redirect all non-file requests to index.html
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  # API proxy to backend (will need to update with actual backend URL)
  from = "/api/*"
  to = "https://your-backend-url.railway.app/api/:splat"
  status = 200
  force = true

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.railway.app https://*.render.com"

[[headers]]
  # Cache static assets
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache JavaScript files
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
