import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAuth, signInWithCustomToken } from 'firebase/auth';
import { RefreshCw, ShieldAlert } from 'lucide-react';

export default function Impersonate() {
  const navigate = useNavigate();
  const [error, setError] = useState(null);
  const [status, setStatus] = useState('Initializing impersonation...');

  useEffect(() => {
    const handleImpersonation = async () => {
      // 1. Get token from hash (safe from server logs)
      const hash = window.location.hash;
      if (!hash || hash.length < 10) {
        setError('Missing or invalid impersonation token.');
        return;
      }

      const token = decodeURIComponent(hash.substring(1));
      const auth = getAuth();

      try {
        setStatus('Authenticating with master authority...');
        // 2. Sign in with the custom token generated by the admin backend
        await signInWithCustomToken(auth, token);
        
        setStatus('Authority verified. Redirecting to merchant workspace...');
        
        // 3. Force reload to clear any stale context and go to app
        setTimeout(() => {
           window.location.href = '/app/dashboard';
        }, 1000);

      } catch (err) {
        console.error('Impersonation failed:', err);
        setError(err.message || 'Verification failed. The token may be expired.');
      }
    };

    handleImpersonation();
  }, []);

  return (
    <div style={{ 
      minHeight: '100vh', 
      display: 'flex', 
      alignItems: 'center', 
      justifyContent: 'center', 
      background: '#0B0F19',
      color: '#fff',
      fontFamily: "'Inter', sans-serif"
    }}>
      <div style={{ textAlign: 'center', maxWidth: '400px', padding: '40px' }}>
        {error ? (
          <div className="fade-in">
            <div style={{ 
              width: '64px', height: '64px', borderRadius: '18px', background: 'rgba(239, 68, 68, 0.1)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px',
              border: '1px solid rgba(239, 68, 68, 0.3)'
            }}>
              <ShieldAlert size={32} color="#ef4444" />
            </div>
            <h2 style={{ fontSize: '20px', fontWeight: 800, marginBottom: '12px' }}>Access Denied</h2>
            <p style={{ color: '#9CA3AF', fontSize: '14px', marginBottom: '24px' }}>{error}</p>
            <button 
              onClick={() => navigate('/admin')}
              style={{ 
                padding: '12px 24px', borderRadius: '8px', background: 'var(--accent, #10b981)',
                border: 'none', color: '#fff', fontWeight: 700, cursor: 'pointer'
              }}
            >
              Return to Terminal
            </button>
          </div>
        ) : (
          <div>
            <div style={{ marginBottom: '24px' }}>
              <RefreshCw size={40} color="#10b981" className="animate-spin" />
            </div>
            <h2 style={{ fontSize: '18px', fontWeight: 800, marginBottom: '8px' }}>Security Handshake</h2>
            <p style={{ color: '#9CA3AF', fontSize: '14px' }}>{status}</p>
            <div style={{ 
              marginTop: '32px', height: '4px', width: '100%', background: 'rgba(255,255,255,0.05)', 
              borderRadius: '2px', overflow: 'hidden' 
            }}>
              <div className="progress-bar-glow" style={{ 
                height: '100%', width: '60%', background: '#10b981', 
                boxShadow: '0 0 10px #10b981'
              }}></div>
            </div>
          </div>
        )}
      </div>
      <style>{`
        .animate-spin { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        .fade-in { animation: fadeIn 0.4s ease-out; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
        .progress-bar-glow { animation: progressMove 2s ease-in-out infinite; }
        @keyframes progressMove { 
          0% { transform: translateX(-100%); }
          100% { transform: translateX(200%); }
        }
      `}</style>
    </div>
  );
}
